version: '3.0'

services:
  node:
    image: node:16.12
    volumes:
      - .:/app    
    ports:
      - 3005:3000
    working_dir: /app
    command: ./node_modules/.bin/nodemon -e ts,json --exec "npm start"